<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>GravityGun</AssemblyName>
    <RootNamespace>GravityGun</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <MineMogulDir Condition="'$(MineMogulDir)' == ''">F:\SteamLibrary\steamapps\common\MineMogul</MineMogulDir>
    <MineMogulManagedDir>$(MineMogulDir)\MineMogul_Data\Managed</MineMogulManagedDir>
    <MineMogulBepInExCoreDir>$(MineMogulDir)\BepInEx\core</MineMogulBepInExCoreDir>
    <MineMogulPluginsDir>$(MineMogulDir)\BepInEx\plugins</MineMogulPluginsDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(MineMogulBepInExCoreDir)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(MineMogulBepInExCoreDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(MineMogulManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(MineMogulManagedDir)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(MineMogulManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(MineMogulManagedDir)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(MineMogulManagedDir)\UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(MineMogulManagedDir)\UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>$(MineMogulManagedDir)\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tool Import API\ToolImportApi.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Assets\Poses\*.arm-pose.cs" />

    <EmbeddedResource Include="Assets\Models\gravity-gun-world.glb">
      <LogicalName>GravityGun.Assets.Models.gravity-gun-world.glb</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Models\gravity-gun-view.glb">
      <LogicalName>GravityGun.Assets.Models.gravity-gun-view.glb</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Images\gravity-gun-icon.png">
      <LogicalName>GravityGun.Assets.Images.gravity-gun-icon.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Poses\*.arm-pose.cs">
      <LogicalName>%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>

    <EmbeddedResource Include="Assets\Audio\gravity-gun-pickup.mp3">
      <LogicalName>GravityGun.Assets.Audio.gravity-gun-pickup.mp3</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Audio\gravity-gun-hold.mp3">
      <LogicalName>GravityGun.Assets.Audio.gravity-gun-hold.mp3</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Audio\gravity-gun-drop.mp3">
      <LogicalName>GravityGun.Assets.Audio.gravity-gun-drop.mp3</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Audio\gravity-gun-shoot.mp3">
      <LogicalName>GravityGun.Assets.Audio.gravity-gun-shoot.mp3</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Audio\gravity-gun-failed-shoot.mp3">
      <LogicalName>GravityGun.Assets.Audio.gravity-gun-failed-shoot.mp3</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
